services:
  # Your existing Node.js app container
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile
    image: rohith230/bt-docker-img:V9
    container_name: bt-docker-container
    ports:
      - "5500:5500"
    depends_on:
      - cadvisor  # Ensure cAdvisor starts before the app container
  
  # cAdvisor container to monitor the application
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"  # Expose cAdvisor on port 8081 on the host, but internally it still uses 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows cAdvisor to access Docker's socket
    restart: always  # Automatically restart the cAdvisor container if it crashes

    # Prometheus container
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Expose port 9090 for Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the Prometheus configuration file
    restart: always

  # Grafana container
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Expose port 3000 for Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password for Grafana
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini  # Mount the Grafana configuration file
    depends_on:
      - prometheus
    restart: always